sb-admin.web/Models/expediente.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sb_admin.web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class expediente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public expediente()
    {

        this.evento = new HashSet<evento>();

        this.documento = new HashSet<documento>();

    }


    public int id { get; set; }

    public string titulo { get; set; }

    public Nullable<System.DateTime> fechacreacion { get; set; }

    public Nullable<System.TimeSpan> hora { get; set; }

    public string descripcion { get; set; }

    public Nullable<int> estadoid { get; set; }

    public Nullable<int> tipoId { get; set; }

    public Nullable<int> claseId { get; set; }

    public Nullable<int> responsableId { get; set; }

    public Nullable<int> ubicacionId { get; set; }

    public int casoId { get; set; }



    public virtual caso caso { get; set; }

    public virtual persona persona { get; set; }

    public virtual tipoExpediente tipoExpediente { get; set; }

    public virtual ubicacion ubicacion { get; set; }

    public virtual claseExpediente claseExpediente { get; set; }

    public virtual estadoExpediente estadoExpediente { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<evento> evento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<documento> documento { get; set; }

}

}

sb-admin.web/Controllers/expedientesController.cs
using sb_admin.web.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace sb_admin.web.Controllers
{
    public class expedientesController : Controller
    {
        private GAHEContext db = new GAHEContext();

        // GET: expedientes
        public async Task<ActionResult> Index()
        {
            var expediente = db.expediente.Include(e =>e.estadoExpediente).Include(e => e.caso).Include(e => e.ubicacion).Include(e => e.claseExpediente).Include(e => e.persona).Include(e => e.tipoExpediente);
            return View(await expediente.ToListAsync());
        }
        // GET: documento/Create
        public async Task<ActionResult> CreateDocumento(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            expediente expediente = await db.expediente.FindAsync(id);
            if (expediente == null)
            {
                return HttpNotFound();
            }

            var documentos = db.documento.Where(d=>d.expedienteIid==id).OrderBy(d => d.fechacreacion).ToList();
            ViewBag.expedienteId = id;           
            return View(documentos);
        }

        [HttpPost]
        public ActionResult SubirArchivo(HttpPostedFileBase file,int id)
        {
            if (file != null && file.ContentLength > 0)
            {
                // Extraemos el contenido en Bytes del archivo subido.
                var _contenido = new byte[file.ContentLength];
                file.InputStream.Read(_contenido, 0, file.ContentLength);

                // Separamos el Nombre del archivo de la Extensión.
                int indiceDelUltimoPunto = file.FileName.LastIndexOf('.');
                string _nombre = file.FileName.Substring(0, indiceDelUltimoPunto);
                string _extension = file.FileName.Substring(indiceDelUltimoPunto + 1,
                                    file.FileName.Length - indiceDelUltimoPunto - 1);
                int _tamano = file.ContentLength;
                string _mime = file.ContentType;
                
                // Instanciamos la clase Archivo y asignammos los valores.
                documento _archivo = new documento()
                {
                    expedienteIid = id,
                    nombre= _nombre,
                    extension=_extension,
                    tamano=_tamano,
                    mime=_mime,
                    creado=1,
                    
                    descripcion="archivo"
                    //Descargas = 0
                };

                try
                {
                    // Subimos el archivo al Servidor.
                    _archivo.SubirArchivo(_contenido);
                    // Guardamos en la base de datos la instancia del archivo
                    db.documento.Add(_archivo);
                        db.SaveChanges();
                    
                }
                catch (Exception ex)
                {
                    // Aquí el código para manejar la Excepción.
                }
            }

            // Redirigimos a la Acción 'Index' para mostrar
            // Los archivos subidos al Servidor.
            return RedirectToAction(string.Format("Details/{0}", id));
        }

        [HttpGet]
        public ActionResult DescargarArchivo(int id)
        {
            documento _archivo;
            FileContentResult _fileContent;

           
                _archivo = db.documento.FirstOrDefault(x => x.id == id);
            

            if (_archivo == null)
            {
                return HttpNotFound();
            }
            else
            {
                try
                {
                    // Descargamos el archivo del Servidor.
                    _fileContent = new FileContentResult(_archivo.DescargarArchivo(),
                                                         "application/octet-stream");
                    _fileContent.FileDownloadName = _archivo.nombre + "_" + _archivo.expedienteIid  +
                                           "." + _archivo.extension;

                   


                    // Actualizamos el nº de descargas en la base de datos.

                    //  _archivo.Descargas++;
                    db.documento.Attach(_archivo);
                        db.Entry(_archivo).State = EntityState.Modified;
                        db.SaveChanges();
                    

                    return _fileContent;
                }
                catch (Exception ex)
                {
                    return HttpNotFound();
                }
            }
        }

        [HttpGet]
        public ActionResult EliminarArchivo(int id)
        {
            documento _archivo;
            _archivo = db.documento.FirstOrDefault(x => x.id == id);
            
            if (_archivo != null)
            {
                _archivo = db.documento.FirstOrDefault(x => x.id == id);
                    db.documento.Remove(_archivo);
                    if (db.SaveChanges() > 0)
                    {
                        // Eliminamos el archivo del Servidor.
                        _archivo.EliminarArchivo();
                    }
                
            // Redirigimos a la Acción 'Index' para mostrar
            // Los archivos subidos al Servidor.
            return RedirectToAction(string.Format("Details/{0}", id));
        }
            else
            {
                return HttpNotFound();
            }
        }
    

    // GET: juzgado_evento/Create
    public async Task<ActionResult> CreateJuzgadoEvento(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            evento evento = await db.evento.FindAsync(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            var juzgado_evento = db.juzgado_evento.Include(j => j.evento).Where(je => je.eventoId == id).Include(j => j.juzgado);
            var juzgado_eventoselectionado = new juzgado_evento { eventoId = evento.id };
           
            ViewBag.juzgadoId = new SelectList(db.juzgado, "id", "nombre");
            return View( juzgado_eventoselectionado);
        }

        // POST: juzgado_evento/Create
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateJuzgadoEvento( juzgado_evento juzgado_evento)
        {
            if (ModelState.IsValid)
            {
                db.juzgado_evento.Add(juzgado_evento);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.eventoId = new SelectList(db.evento, "id", "descripcion_evento", juzgado_evento.eventoId);
            ViewBag.juzgadoId = new SelectList(db.juzgado, "id", "nombre", juzgado_evento.juzgadoId);
            return View(juzgado_evento);
        }

        // GET: eventos/Edit/5
        public async Task<ActionResult> EditEvento(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            evento evento = await db.evento.FindAsync(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
         
            ViewBag.servicioId = new SelectList(db.servicio, "id", "descripcion", evento.servicioId);
            ViewBag.tipo_evento = new SelectList(db.tipo_evento, "id", "tipo_evento1", evento.tipo_evento);
            return View(evento);
        }

        // POST: eventos/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditEvento(evento evento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(evento).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction(string.Format("Details/{0}", evento.expedienteId));
            }
          
            ViewBag.servicioId = new SelectList(db.servicio, "id", "descripcion", evento.servicioId);
            ViewBag.tipo_evento = new SelectList(db.tipo_evento, "id", "tipo_evento1", evento.tipo_evento);
            return View(evento);
        }
        // GET: eventos/Create
        public async Task<ActionResult> CreateEvento(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            expediente expediente = await db.expediente.FindAsync(id);
            if (expediente == null)
            {
                return HttpNotFound();
            }



            var evento = new evento { expedienteId= expediente.id };
            ViewBag.juzgadoId = new SelectList(db.juzgado, "id", "nombre");
            ViewBag.servicioId = new SelectList(db.servicio, "id", "descripcion");
            ViewBag.tipo_evento = new SelectList(db.tipo_evento, "id", "tipo_evento1");
            return View(evento);
        }

        // POST: eventos/Create
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateEvento(evento evento)
        {
            if (ModelState.IsValid)
            {
                db.evento.Add(evento);
                await db.SaveChangesAsync();
                return RedirectToAction(string.Format("Details/{0}",evento.expedienteId));
            }

          
            ViewBag.servicioId = new SelectList(db.servicio, "id", "descripcion", evento.servicioId);
            ViewBag.tipo_evento = new SelectList(db.tipo_evento, "id", "tipo_evento1", evento.tipo_evento);
            return View(evento);
        }

        // GET: eventos/Delete/5

sb-admin.web/Views/expedientes/Create.cshtml
@model sb_admin.web.Models.expediente

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>expediente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechacreacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechacreacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechacreacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estadoid,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("estadoId", null, "Seleccione El estado de Expediente", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.estadoid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipoId,  htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("tipoId", null,"Seleccione El tipo de Expediente" , htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tipoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.claseId,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("claseId", null,"Seleccione clase", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.claseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.responsableId,  htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

               @Html.DropDownList("responsableId", null, "seleccione responsable" ,htmlAttributes: new { @class = "form-control" })
               @Html.ValidationMessageFor(model => model.responsableId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ubicacionId,  htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ubicacionId", null, "Seleccione Ubicación ",htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ubicacionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.casoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("casoId", null,"Seleccione el caso del expediente",  htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.casoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(" Regresar a Listado", "Index",null,new { @class="btn btn-success btn-sm fa fa-backward"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

sb-admin.web/Views/expedientes/CreateDocumento.cshtml
@model IEnumerable<sb_admin.web.Models.documento>

@{
    ViewBag.Title = "Crear Documento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear Documento</h2>
<br />

<div class="container">
    @using (Html.BeginForm("SubirArchivo", "expedientes", new { id=ViewBag.expedienteId},
                FormMethod.Post,
                new { enctype = "multipart/form-data", method = "post" }))
    {
       
       
        <div class="row">
            <div class="col-sm-6">
                <input type="file" name="file" />
            </div>
            <div class="col-md-6 left">
                <button type="submit" class="btn btn-sm btn-primary">
                    <span class="glyphicon glyphicon-open"></span>
                    &nbsp;Subir archivo
                </button>
            </div>
        </div>
    }
    <hr />
    <div class="row">
        <div class="col-md-12">
            @foreach (var item in Model)
            {
                <span>@item.fechacreacion.ToShortDateString() - </span>
                <a href="@Url.Action("DescargarArchivo", "expedientes", new { id = item.id })">
                    <span class="glyphicon glyphicon-save"></span>
                    <span>@item.nombre.@item.extension</span>
                </a>
                @* <span> - Descargas: @item.Descargas - </span> *@
                <a href="@Url.Action("EliminarArchivo", "expedientes",
                         new { id = item.id })" class="text-danger">
                    <span class="glyphicon glyphicon-remove text-danger small"></span>
                    Eliminar archivo
                </a>
                <br />
            }
        </div>
    </div>
</div>

sb-admin.web/Views/expedientes/CreateEvento.cshtml
@model sb_admin.web.Models.evento

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear evento</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>evento</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.expedienteId)

    <div class="form-group">
        @Html.LabelFor(model => model.tipo_evento,  htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("tipo_evento", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.tipo_evento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.descripcion_evento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.descripcion_evento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descripcion_evento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fecha_inicio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fecha_inicio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fecha_inicio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.servicioId,  htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("servicioId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.servicioId, "", new { @class = "text-danger" })
        </div>
    </div>

    
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-sm btn-primary"> />
          
            @Html.ActionLink("Regresar a Expediente", "Details", new { id = Model.expedienteId }, new { @class = "btn btn-success btn-sm" })
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

sb-admin.web/Views/expedientes/CreateJuzgado.cshtml
@model IEnumerable<sb_admin.web.Models.juzgado>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Juzgados</h2>

<p>
    @Html.ActionLink("Nuevo Juzgado", "Create", null, new { @class = "btn btn-sm btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lugar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.piso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ciudad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombre_juez)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.apellido_juez)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th>
           @Html.DisplayNameFor(model => model.tipo_juzgado.tipo_j)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lugar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.piso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ciudad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre_juez)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.apellido_juez)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tipo_juzgado.tipo_j)
            </td>
            <td>
                @Html.ActionLink("Select", "CreateJuzgado", new { id = ViewBag.idEvento, idjuzgado = item.id }) |
            </td>
        </tr>
    }

</table>

sb-admin.web/Views/expedientes/CreateJuzgadoEvento.cshtml
@model sb_admin.web.Models.juzgado_evento

@{
    ViewBag.Title = "CreateJuzgadoEvento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateJuzgadoEvento</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Juzgado Evento</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.eventoId)

    <div class="form-group">
        @Html.LabelFor(model => model.juzgadoId, "juzgadoId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("juzgadoId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.juzgadoId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

sb-admin.web/Views/expedientes/Delete.cshtml
@model sb_admin.web.Models.expediente

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>expediente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechacreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechacreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hora)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hora)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estadoid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estadoid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.caso.referencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.caso.referencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ubicacion.ubicacion1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ubicacion.ubicacion1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.claseExpediente.Clase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.claseExpediente.Clase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.persona.dni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.persona.dni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipoExpediente.tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipoExpediente.tipo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink(" Regresar a Listado", "Index",null,new { @class="btn btn-success btn-sm fa fa-backward"})
        </div>
    }
</div>

sb-admin.web/Views/expedientes/DetailsJuzgado.cshtml
@model IEnumerable<sb_admin.web.Models.juzgado_evento>

@{
    ViewBag.Title = "DetailsJuzgado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DetailsJuzgado</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.juzgado.juzgado_evento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.evento.descripcion_evento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.juzgado.nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.juzgado.juzgado_evento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.evento.descripcion_evento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.juzgado.nombre)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>